---
- name: install sos
  package:
    name: sos
    state: present

- name: get platform-python site path
  command: /usr/libexec/platform-python -c 'from distutils.sysconfig import get_python_lib; print(get_python_lib())'
  register: get_python_lib_result
  changed_when: False

- name: set platform_python_site_packages
  set_fact:
    platform_python_site_packages: "{{ get_python_lib_result.stdout }}"

- name: copy in CitC sosreport plugin
  copy:
    src: citc.py
    dest: "{{ platform_python_site_packages }}/sos/report/plugins/citc.py"
    owner: root
    group: root
    mode: 0644

- name: update SOS config compression to gzip
  copy:
    src: sos.conf
    dest: /etc/sos.conf
    owner: root
    group: root
    mode: u=rw,g=r,o=r
